### ISSUE TITLE
Use SwSpotify to get local Spotify metadata and lyrics

### ISSUE THREAD

**Issue by andriyor** [marioortizmanero/spotify-music-videos#10]
You can use https://github.com/SwagLyrics/SwSpotify - cross-platform library for receiving current playing track

**Comment by marioortizmanero** [comment]
Oh, very interesting. I didn't know you could do that on Windows. I'll take a look to all of SwagLyrics when I have more time for sure, since it also seems to have a Genius scraper. But I don't know how reliable it would be in comparison to Lyricwikia.

Thanks for sharing!

**Comment by marioortizmanero** [comment]
So after checking this a bit, the APIs from windows and macOS are a bit limited because they aren't APIs, the module just reads the windows title. So things like knowing if the music is playing or stopped wouldn't work unless I find a workaround. Also, I currently don't have a macOS so I'm not sure how I could implement that without testing.

**Comment by marioortizmanero** [comment]
This has been implemented in the `next` branch and needs a few more tests before it can go stable. Thanks to you and the creator of SwSpotify!

**Comment by aadibajpai** [comment]
> So after checking this a bit, the APIs from windows and macOS are a bit limited because they aren't APIs, the module just reads the windows title. So things like knowing if the music is playing or stopped wouldn't work unless I find a workaround. Also, I currently don't have a macOS so I'm not sure how I could implement that without testing.

Would you be interested in knowing if the music is paused or stopped? Right now, both things raise the SpotifyNotRunning exception but I know that we can differentiate between the two. Hasn't been implemented yet since I didn't find a use case and I'm not sure about all OSes. Can be done for windows easily since when it is paused, the window title reads "Spotify Free" or "Spotify Premium".

**Comment by aadibajpai** [comment]
Also, there's one thing I'm confused about. I think the linux part of SwSpotify uses the same approach as your approach with dbus, so did you do something different here that provides better functionality? If so, it would be great to have that in SwSpotify too!

**Comment by marioortizmanero** [comment]
> > So after checking this a bit, the APIs from windows and macOS are a bit limited because they aren't APIs, the module just reads the windows title. So things like knowing if the music is playing or stopped wouldn't work unless I find a workaround. Also, I currently don't have a macOS so I'm not sure how I could implement that without testing.
> 
> Would you be interested in knowing specifically if the music is paused or stopped? Right now, both things raise the [SpotifyNotRunning](https://github.com/SwagLyrics/SwSpotify/blob/master/SwSpotify/__init__.py) exception that can be handled by default but I know that we can differentiate between the two.
> 
> Hasn't been implemented yet since I didn't find a use case and I'm not sure about all OSes. Can be done for windows easily since when it is paused, the window title reads "Spotify Free" or "Spotify Premium".

I was going to implement this myself but it'd be very helpful this way!

My dbus approach is more advanced than what SwSpotify allows, since I have a main loop to check for events inside it, and it also checks the status of the player (playing/paused). But anything from there can be passed to SwSpotify if you want, the license I'm using is MIT.

Another important part is that when SwSpotify calls `get_info_xxxx`, it creates a new dbus session bus, connects to it, etc, while in mine I only connect to it once.

**Comment by aadibajpai** [comment]
> > > So after checking this a bit, the APIs from windows and macOS are a bit limited because they aren't APIs, the module just reads the windows title. So things like knowing if the music is playing or stopped wouldn't work unless I find a workaround. Also, I currently don't have a macOS so I'm not sure how I could implement that without testing.
> > 
> > 
> > Would you be interested in knowing specifically if the music is paused or stopped? Right now, both things raise the [SpotifyNotRunning](https://github.com/SwagLyrics/SwSpotify/blob/master/SwSpotify/__init__.py) exception that can be handled by default but I know that we can differentiate between the two.
> > Hasn't been implemented yet since I didn't find a use case and I'm not sure about all OSes. Can be done for windows easily since when it is paused, the window title reads "Spotify Free" or "Spotify Premium".
> 
> I was going to implement this myself but it'd be very helpful this way!
> 
> My dbus approach is more advanced than what SwSpotify allows, since I have a main loop to check for events inside it, and it also checks the status of the player (playing/paused). But anything from there can be passed to SwSpotify if you want, the license I'm using is MIT.
> 
> Another important part is that when SwSpotify calls `get_info_xxxx`, it creates a new dbus session bus, connects to it, etc, while in mine I only connect to it once. So maybe using a different class for each platform you support and then instantiate the object instead of having a function call would be helpful. But maybe too advanced for what SwSpotify seems to be? I'm not sure what the objective of SwSpotify is

I feel the main idea is to be fast and cross-platform so a developer can make their application work on all OSes right out of the box. I'll work on the paused and not running differentiation but I might not be able to get to it until the weekend now. 

The thing is, my primary OS is Windows so I haven't tested the linux and macOS part that thoroughly. The multiple bus thing really sounds inefficient so it would be nice to improve that further. I'd be glad if you could provide a PR, maybe, since it looks like you're on Linux. Also, what do you mean by the main loop to check for events, does it do something different? It would be good to modify it to detect the play/pause thing too if that's helpful. Maybe you could open an issue over at SwSpotify so we can discuss the implementation further? I have an idea on how to do it for Windows but not so much for Linux.

Thanks for letting me know this btw, I'm really interested in developing it further!

**Comment by marioortizmanero** [comment]
I'm also having trouble with testing because I do have a windows VM but I haven't been able to get a macOS VM running. Here's the continuation issue: https://github.com/SwagLyrics/SwSpotify/issues/3

**Comment by marioortizmanero** [comment]
This has been implemented in 2.0, which should be available in January of 2020 (unfortunately the new Spotify Web API is going to take a while to settle down). Thanks a bunch to both of you for helping this project out :)

**Comment by aadibajpai** [comment]
> This has been implemented in 2.0, which should be available in January of 2020 (unfortunately the new Spotify Web API is going to take a while to settle down). Thanks a bunch to both of you for helping this project out :)

Neat! What do you depend on the Web API for btw?

**Comment by marioortizmanero** [comment]
It's [spotipy](https://github.com/felix-hilden/spotipy). The original one was [this](https://github.com/plamere/spotipy), but it hasn't been updated in 2 years and the maintainer isn't answering issues or mails. So this new API has to transfer the PyPi repository and the Read The Docs page.
